# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b842a4bb7cd97bdf0970593d56ad25247abe306cec69d477b18bd2f2a463eb70fe19861d7350c9e5ca927de8cf9fa8cea470c37338d2074c5ecf61699ea02d37

test:
  secret_key_base: be4463e9b27da23f7fd5c0b6b22c32ade15ce09485264e525ec3a2bd88bd9004461dbf94007304856b345b81885d2fba1f3a8433b6efe46d7437070c5cd3f421

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
